name: go_build

on:
  release:
    types: [created]

jobs:
  build:
    name: build_to_release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux]
        goarch: [amd64]
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Set APP_VERSION env
      run: echo APP_VERSION=$(git rev-parse --short "$GITHUB_SHA") >> ${GITHUB_ENV}

    - name: Build gorkscrew binary
      uses: wangyoucao577/go-release-action@master
      with:
        github_token: ${{ secrets.TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        # goversion: "https://dl.google.com/go/go${{ steps.go_version.outputs.prop }}.linux-amd64.tar.gz"
        # ldflags: "-X 'main.GorkscrewVersion=${{ env.APP_VERSION }}' -X 'main.GoVersion=${{ steps.go_version.outputs.prop }}'"